<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb0b9cd40b308ede5719272a04643bfdb
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Picqer\\Barcode\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Picqer\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/picqer/php-barcode-generator/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb0b9cd40b308ede5719272a04643bfdb::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb0b9cd40b308ede5719272a04643bfdb::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb0b9cd40b308ede5719272a04643bfdb::$classMap;

        }, null, ClassLoader::class);
    }
}
